version: '3.3'
services:
    apacheweb:
      build:
        context: .
        dockerfile: ./web/Dockerfile
        args:
          - MARIADB_PASSWORD=${MARIADB_PASSWORD}
          - DB_HOST=db            
      container_name: apacheweb
      env_file:
        - .env
      depends_on: 
        - db
      ports:
        - 8080:80
      networks:
        - net_lamp
    db:
      build:
        context: .
        dockerfile: ./db/Dockerfile
      container_name: db
      environment:
        - MARIADB_USER=${MARIADB_USER}
        - MARIADB_PASSWORD=${MARIADB_PASSWORD}
        - MARIADB_DATABASE=${MARIADB_DATABASE}
        - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      env_file:
        - .env
      networks:
        - net_lamp
networks:
  net_lamp: